version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '5000:5000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: http://13.60.242.232:5000
        VITE_SOCKET_URL: http://13.60.242.232:5000
    ports:
      - '3000:3000'
